# Generated by Django 2.2 on 2019-05-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systemeventlogentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='system',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='systemeventlogentry',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
