# Generated by Django 2.2 on 2019-05-21 22:24

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20190502_1929'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubFirmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sync_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('fw', models.FileField(blank=True, default='', upload_to='')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
