# Generated by Django 2.2.1 on 2019-05-22 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0004_hubfirmware'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubfirmware',
            name='fw',
            field=models.FileField(blank=True, default='', upload_to='assets/firmware/'),
        ),
    ]
