# Generated by Django 2.2.1 on 2019-05-29 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_auto_20190522_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubfirmware',
            name='version',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
