# Generated by Django 2.2.7 on 2020-01-13 22:29

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0006_hubfirmware_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sync_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('build_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['build_date', 'created'],
            },
        ),
        migrations.CreateModel(
            name='TagBuild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sync_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('build_date', models.DateTimeField(default=None, null=True)),
            ],
            options={
                'ordering': ['build_date', 'created'],
            },
        ),
        migrations.DeleteModel(
            name='Hub',
        ),
    ]
