# Generated by Django 2.2.7 on 2020-01-13 23:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0008_auto_20200113_2345'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagFirmware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('sync_id', models.PositiveIntegerField(null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('version', models.CharField(max_length=255, null=True)),
                ('fw', models.FileField(blank=True, default='', upload_to='assets/firmware/tag/')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='system',
            name='manufacture_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='tag',
            name='manufacture_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='hubfirmware',
            name='fw',
            field=models.FileField(blank=True, default='', upload_to='assets/firmware/hub/'),
        ),
        migrations.AddField(
            model_name='tag',
            name='firmware',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firmware_tags', to='system.TagFirmware'),
        ),
    ]
