# Generated by Django 2.2.1 on 2019-05-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0002_auto_20190502_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='teams',
            field=models.ManyToManyField(related_name='members', to='org.Team'),
        ),
    ]
