# Generated by Django 2.2.1 on 2019-05-30 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0004_orgmemberpermission_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgmember',
            name='permissions',
            field=models.ManyToManyField(related_name='permission_org_members', to='org.Permission'),
        ),
    ]
