# Generated by Django 2.2.1 on 2019-10-17 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0005_orgmember_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgmember',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='org.Team'),
        ),
    ]
