# Generated by Django 2.2.1 on 2019-11-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0007_feature_orgfeature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
