# Generated by Django 2.1.7 on 2019-03-28 21:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_activitydata_est_bak'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydata',
            name='sensors',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
