# Generated by Django 2.2 on 2019-04-23 18:12

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_auto_20190401_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydata',
            name='io_event',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
