# Generated by Django 2.2 on 2019-05-02 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0005_activitydata_io_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitydata',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='activitytype',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='session',
            name='sync_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
