# Generated by Django 2.2.1 on 2019-05-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20190502_1929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitytype',
            options={},
        ),
        migrations.AddConstraint(
            model_name='activitytype',
            constraint=models.UniqueConstraint(fields=('type_obj',), name='unique_draft_user'),
        ),
    ]
