# Generated by Django 2.2.7 on 2020-01-08 22:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracking', '0008_activityfav'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activityfav',
            unique_together={('activity', 'user')},
        ),
    ]
