# Generated by Django 2.2.7 on 2020-01-09 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_auto_20200108_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityfav',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fav_users', to='tracking.Activity'),
        ),
    ]
