# Generated by Django 2.2.7 on 2020-03-10 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_activityannotation'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='stats_type',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
